### PR TITLE
Append log message to help to understand autoreply mechanism

### PR DESCRIPTION
**Pull request by harobed**
What do you think about this patch ? It's help to debug and understand autoreply mechanism.

### CODE REVIEW

**Comment by tonioo** [comment]
It could be useful but I think you should add a dedicated option to activate this feature. (like a --debug or --verbose one)

**Comment by harobed** [comment]
> It could be useful but I think you should add a dedicated option to activate this feature. (like a --debug or --verbose one)

Ok, I'll do it.

**Comment by harobed** [comment]
> It could be useful but I think you should add a dedicated option to activate this feature. (like a --debug or --verbose one)

Fixed now I use logging + -d switch option.

**Comment by harobed** [comment]
Thanks

**Pull request merged**
