### PR TITLE
SuperAdmins and DomainAdmins can see and update all its domain mailbox autoreply messages

### PR DESCRIPTION
**Pull request by harobed**
SuperAdmins and DomainAdmins can see and update all its domain mailbox autoreply messages.

### CODE REVIEW

**Comment by tonioo** [comment]
Looks like a nice feature, thank you. Do you know why unit tests are failing ?

**Comment by harobed** [comment]
Bug fixed here : https://github.com/modoboa/modoboa-postfix-autoreply/pull/17

**Comment by tonioo** [comment]
Thanks!

**Comment by tonioo** [comment]
Finally, it looks like I merged your PR too quickly :

1) It was already possible to enable/disable the ar of a user (a checkbox is available in the mail form). Since you include the form without modification, there are now two checkboxes for the same action.
2) The subject and content fields are mandatory, so when your edit an account, you have to fill them. It is not a good behaviour since the user may not have defined its ar message yet.

Another issue: the ARmessage instance of a mailbox is not automatically created. It will be the first time a user define an autoreply message. So, if you try to save a user account (as admin) which does not have a message defined, it fails with a 500 error. This is why unit tests currently fail on the master branch.

Could you take a look at this and try to fix it please ?

**Pull request merged**
